name: Bug report
description: Report a bug
labels: ["bug"]
body:
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "macOS 15.2 / Ubuntu 24.04 / ..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "v1.0.0"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Paste relevant output from `~/.claude/scripts/sync.log`."
      render: text
